The notebook is written for a better understanding of the Embedding layer. How a sentence is given to the neural network model is explained step by step. 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
cd /content/drive/My Drive/Phd_implementation/FDP_exp_2020/Day3

/content/drive/My Drive/Phd_implementation/FDP_exp_2020/Day3


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np
from numpy import array
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Embedding, Dense
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
reviews = [
    'Never coming back!',
    'Horrible service',
    'Rude waitress',
    'Cold food.',
    'Horrible food!',
    'Awesome',
    'Awesome service!',
    'Rocks!',
    'poor work',
    'Couldn\'t have done better']

# Define labels (1=negative, 0=positive)
labels = array([1,1,1,1,1,0,0,0,0,0])

In [5]:
reviews

['Never coming back!',
 'Horrible service',
 'Rude waitress',
 'Cold food.',
 'Horrible food!',
 'Awesome',
 'Awesome service!',
 'Rocks!',
 'poor work',
 "Couldn't have done better"]

In [0]:
tokenizer = Tokenizer(lower= True)
tokenizer.fit_on_texts(reviews)


In [7]:
tokenizer.word_index

{'awesome': 4,
 'back': 7,
 'better': 17,
 'cold': 10,
 'coming': 6,
 "couldn't": 14,
 'done': 16,
 'food': 3,
 'have': 15,
 'horrible': 1,
 'never': 5,
 'poor': 12,
 'rocks': 11,
 'rude': 8,
 'service': 2,
 'waitress': 9,
 'work': 13}

In [0]:
VOCAB_SIZE = len(tokenizer.word_index)

In [9]:
VOCAB_SIZE

17

In [0]:
word_index = tokenizer.word_index

In [0]:
data_sequence = tokenizer.texts_to_sequences(reviews)

In [12]:
data_sequence

[[5, 6, 7],
 [1, 2],
 [8, 9],
 [10, 3],
 [1, 3],
 [4],
 [4, 2],
 [11],
 [12, 13],
 [14, 15, 16, 17]]

In [13]:
padded_reviews = pad_sequences(data_sequence, maxlen=4, padding='post')
print(padded_reviews)

[[ 5  6  7  0]
 [ 1  2  0  0]
 [ 8  9  0  0]
 [10  3  0  0]
 [ 1  3  0  0]
 [ 4  0  0  0]
 [ 4  2  0  0]
 [11  0  0  0]
 [12 13  0  0]
 [14 15 16 17]]


In [14]:
model = Sequential()
embedding_layer = Embedding(input_dim = VOCAB_SIZE+1, output_dim= 8, input_length=4)
model.add(embedding_layer)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              144       
Total params: 144
Trainable params: 144
Non-trainable params: 0
_________________________________________________________________
None


In [15]:
embedding_layer_weight = embedding_layer.get_weights()
embedding_layer_weight

[array([[ 1.04780085e-02, -1.68743953e-02,  3.49558890e-04,
          2.69836448e-02,  2.41280682e-02,  7.76081160e-03,
          2.54145972e-02, -4.67395075e-02],
        [-2.06414219e-02, -8.30620527e-03,  2.96196006e-02,
          3.90830524e-02, -3.71533521e-02,  2.74536721e-02,
         -1.20817535e-02,  3.01398076e-02],
        [ 4.47013266e-02, -2.19367035e-02,  5.17636538e-03,
         -3.61812003e-02,  3.56983431e-02,  1.27136819e-02,
          3.37710641e-02,  8.78258795e-03],
        [ 2.20942236e-02,  2.31656171e-02, -4.22840491e-02,
          1.38324834e-02,  3.48441638e-02, -1.39672272e-02,
          4.84380461e-02, -3.21456045e-03],
        [-2.81402227e-02, -2.29115617e-02, -1.09022260e-02,
         -1.29757747e-02,  3.71506847e-02,  2.57416479e-02,
          3.69223617e-02, -1.14641339e-03],
        [-1.73501857e-02, -2.86739822e-02,  3.23587656e-03,
         -2.97007561e-02,  1.00709796e-02,  1.84364803e-02,
         -2.74860393e-02,  2.68659331e-02],
        [ 4.1670

In [16]:
embedding_layer_weight[0].shape

(18, 8)

In [0]:
#embedding_layer_weight[0][0]

In [17]:
pred = model.predict(padded_reviews)
pred


array([[[-1.73501857e-02, -2.86739822e-02,  3.23587656e-03,
         -2.97007561e-02,  1.00709796e-02,  1.84364803e-02,
         -2.74860393e-02,  2.68659331e-02],
        [ 4.16708477e-02,  1.72731765e-02, -3.36337313e-02,
         -6.48975372e-03, -3.67143005e-03, -2.61869188e-02,
          4.50980775e-02, -1.79371722e-02],
        [ 2.87590064e-02,  1.48288347e-02, -8.74508545e-03,
          2.45848931e-02, -4.21644822e-02,  3.99160385e-03,
         -6.47131354e-03,  3.08592580e-02],
        [ 1.04780085e-02, -1.68743953e-02,  3.49558890e-04,
          2.69836448e-02,  2.41280682e-02,  7.76081160e-03,
          2.54145972e-02, -4.67395075e-02]],

       [[-2.06414219e-02, -8.30620527e-03,  2.96196006e-02,
          3.90830524e-02, -3.71533521e-02,  2.74536721e-02,
         -1.20817535e-02,  3.01398076e-02],
        [ 4.47013266e-02, -2.19367035e-02,  5.17636538e-03,
         -3.61812003e-02,  3.56983431e-02,  1.27136819e-02,
          3.37710641e-02,  8.78258795e-03],
        [ 1.04

In [18]:
pred[0]

array([[-0.01735019, -0.02867398,  0.00323588, -0.02970076,  0.01007098,
         0.01843648, -0.02748604,  0.02686593],
       [ 0.04167085,  0.01727318, -0.03363373, -0.00648975, -0.00367143,
        -0.02618692,  0.04509808, -0.01793717],
       [ 0.02875901,  0.01482883, -0.00874509,  0.02458489, -0.04216448,
         0.0039916 , -0.00647131,  0.03085926],
       [ 0.01047801, -0.0168744 ,  0.00034956,  0.02698364,  0.02412807,
         0.00776081,  0.0254146 , -0.04673951]], dtype=float32)

In [19]:
padded_reviews[0]

array([5, 6, 7, 0], dtype=int32)

In [20]:
embedding_layer_weight[0][5]

array([-0.01735019, -0.02867398,  0.00323588, -0.02970076,  0.01007098,
        0.01843648, -0.02748604,  0.02686593], dtype=float32)

In [21]:
#load pre-trained embedding:
embeddings_index = {}
f = open('glove.twitter.27B.25d.txt', encoding="utf8")
for line in f:
    values = line.split()#This splits each values in a  line with spaces
    word = values[0] # This store the first values which is the word in english
    coefs = np.asarray(values[1:], dtype='float32') # This converts all splitted values from 1 to last(expect first word) into an array
    embeddings_index[word] = coefs # english word = array of numerical values
f.close()
print('Total %s word vectors in Glove 6B 100d.' % len(embeddings_index))

Total 1193514 word vectors in Glove 6B 100d.


In [0]:
# Initialize the weight for each word for the embedding layer. Words not present
# in the dictionary initialized by random value 
EMBEDDING_DIM = 25
embedding_matrix = np.random.random((len(word_index) + 1, EMBEDDING_DIM))
#embedding_matrix = (16433, 100) NOTE: It is from uniques words in our tweets
for word, i in word_index.items(): # Selecting word from our tweet unique words list for changing with the values from glove
    embedding_vector = embeddings_index.get(word) # Finding our tweet words in glove and taking its array of 100 values
    if embedding_vector is not None: 
#words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector


In [23]:
model = Sequential()
embedding_layer = Embedding(input_dim = VOCAB_SIZE+1, output_dim = 25, weights=[embedding_matrix], input_length=4, trainable = False)
model.add(embedding_layer)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 25)             450       
Total params: 450
Trainable params: 0
Non-trainable params: 450
_________________________________________________________________
None


In [24]:
embedding_layer_weight = embedding_layer.get_weights()
embedding_layer_weight

[array([[ 0.15154812,  0.28688595,  0.52621865,  0.27453825,  0.1888293 ,
          0.73825365,  0.2665971 ,  0.02117676,  0.55655235,  0.76418984,
          0.8533627 ,  0.83069444,  0.01616171,  0.04909716,  0.35011744,
          0.59594524,  0.14466196,  0.7726717 ,  0.7603559 ,  0.4395144 ,
          0.3285634 ,  0.46561593,  0.4289492 ,  0.7472949 ,  0.03469571],
        [ 0.21438   , -0.66014   , -0.16823   ,  0.27111   ,  0.75163   ,
          1.4539    ,  1.3342    ,  0.45775   , -1.0655    , -0.43815   ,
         -0.3065    , -1.0593    , -3.0458    ,  0.15611   ,  1.9577    ,
          1.2217    ,  0.35779   ,  0.4452    , -0.34816   , -0.47898   ,
          0.62939   ,  0.82832   ,  0.74702   ,  0.15725   , -0.10929   ],
        [-0.30753   ,  0.88404   , -1.0297    , -0.61819   ,  1.0883    ,
         -0.51168   ,  0.20697   , -0.43241   ,  1.2657    ,  0.45289   ,
          0.51967   ,  0.050615  , -3.8389    ,  0.59332   ,  1.0632    ,
          0.32348   ,  0.85886   , -

In [25]:
embedding_layer_weight[0].shape

(18, 25)

In [26]:
pred_glove = model.predict(padded_reviews)
pred_glove

array([[[ 0.35787   ,  0.53172   ,  0.02891   , -0.11454   ,
         -0.9309    , -0.058475  ,  1.6786    , -0.26025   ,
         -0.79749   , -0.29905   , -0.049528  ,  0.37763   ,
         -5.4355    , -0.14486   , -0.4962    ,  0.98797   ,
          0.12834   , -0.033029  ,  0.52323   , -1.0346    ,
          0.55156   ,  0.7415    ,  0.20227   ,  0.67147   ,
          0.036255  ],
        [-0.72052   ,  0.77606   ,  0.58006   , -0.76466   ,
         -0.45005   , -0.21402   ,  1.5047    , -0.40918   ,
         -0.43951   , -0.14405   , -0.1272    ,  0.72284   ,
         -4.3729    ,  0.51053   ,  0.42036   ,  0.035156  ,
         -0.10893   , -0.75633   , -0.63182   , -0.35142   ,
         -0.31829   , -0.71342   ,  0.51693   ,  0.10108   ,
          0.48018   ],
        [-0.74355   ,  0.715     , -0.1593    , -0.28136   ,
         -0.736     , -0.17702   ,  1.0432    ,  0.62863   ,
         -1.0324    ,  0.44264   , -0.11356   ,  0.30086   ,
         -4.7917    , -0.22962   , -0.2

In [27]:
pred_glove[0]

array([[ 0.35787   ,  0.53172   ,  0.02891   , -0.11454   , -0.9309    ,
        -0.058475  ,  1.6786    , -0.26025   , -0.79749   , -0.29905   ,
        -0.049528  ,  0.37763   , -5.4355    , -0.14486   , -0.4962    ,
         0.98797   ,  0.12834   , -0.033029  ,  0.52323   , -1.0346    ,
         0.55156   ,  0.7415    ,  0.20227   ,  0.67147   ,  0.036255  ],
       [-0.72052   ,  0.77606   ,  0.58006   , -0.76466   , -0.45005   ,
        -0.21402   ,  1.5047    , -0.40918   , -0.43951   , -0.14405   ,
        -0.1272    ,  0.72284   , -4.3729    ,  0.51053   ,  0.42036   ,
         0.035156  , -0.10893   , -0.75633   , -0.63182   , -0.35142   ,
        -0.31829   , -0.71342   ,  0.51693   ,  0.10108   ,  0.48018   ],
       [-0.74355   ,  0.715     , -0.1593    , -0.28136   , -0.736     ,
        -0.17702   ,  1.0432    ,  0.62863   , -1.0324    ,  0.44264   ,
        -0.11356   ,  0.30086   , -4.7917    , -0.22962   , -0.21154   ,
        -0.14965   , -0.31582   , -1.3908    , -0

In [0]:
never 0.35787 0.53172 0.02891 -0.11454 -0.9309 -0.058475 1.6786 -0.26025 -0.79749 -0.29905 -0.049528 0.37763 -5.4355 -0.14486 -0.4962 0.98797 0.12834 -0.033029 0.52323 -1.0346 0.55156 0.7415 0.20227 0.67147 0.036255

